---
title: "Reseña de *Lo sagrado y lo profano* de Mircea Eliade"
author: "JJ Merelo, `jjmerelo@correo.ugr.es`"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
bibliography: biblio.bib
abstract: |
  "Lo sagrado y lo profano" aporta una serie de claves a la interpretación de la obra artística con motivo u origen religioso, pero también a muchas obras arquitectónicas y obras visuales figurativas. La visión del mundo a través de la experiencia humana de lo sagrado permite entender mejor el significado de elementos arquitectónicos, pictóricos y escultóricos desde el inicio de las civilizaciones
---

## Edición

"Lo sagrado y lo profano", de Mircea Eliade, traducido por Luis Gil Fernández. Colección Punto Omega. Guadarrama, Madrid, 1967.

## Resumen

En este libro, editado en 1956 en alemán por primera vez, Mircea Eliade introduce una serie de conceptos relacionados con la experiencia religiosa extraídos de sus estudios de las religiones y textos sagrados de la Antigüedad. La obra se divide en varias partes:

* Una introducción, donde habla de la manifestación de "lo sagrado" e introduce una serie de términos relacionados con la misma.
* Un primer capítulo dedicado al *espacio* sagrado.
* Un segundo capítulo dedicado al *tiempo* sagrado.
* Un tercer capítulo en el que analiza la la experiencia religiosa en la relación con la Naturaleza.
* Finalmente, un cuarto capítulo donde habla cómo la existencia humana se puede santificar, es decir, formar parte de lo sagrado.

La introducción establece las pautas fundamentales del libro, sentando las bases de lo que se considera "sagrado" en oposición a lo que no tiene ese carácter, llamado en general profano.

> La manifestación de lo sagrado fundamenta ontológicamente el mundo (p. 4)^[Al tratarse de una edición digital, los números de página no se corresponden a los que hay en la edición física]

Esta manifestación de lo sagrado, sentida individualmente como una experiencia de lo mismo, se denomina *hierofanía*, y Eliade afirma que es lo que le proporciona al mundo su entidad, su ser. La experiencia de lo sagrado, por tanto, le da sentido al mundo. En la descripción de esta experiencia menciona *Das Heilige*, de Rudolf Otto [@otto1926das], y cómo analiza el mismo las diferentes fases o "momentos" que puede adoptar esta experiencia religiosa, dentro de una experiencia que se define como *numinosa* e "irracional"; Mircea Eliade toma esa definición y la amplía, hablando de una experiencia *ganz andere* (en alemán, "todo otro"), es decir, totalmente diferente a la experiencia normal de la realidad, definible con palabras, y por lo tanto *inefable*. Se opone, por tanto, a "lo profano", aquello que forma parte de la experiencia sensorial y que por tanto hay palabras para definir.

Sin embargo, se afirma que, aunque no haya palabras para definirlo por ser *sui generis*, algunos aspectos de la experiencia sagrada sí se pueden definir. Retomando los "momentos" de Otto [@otto1926das], lo sagrado equivale al poder y por tanto, no sólo a la realidad por antonomasia, sino incluso al origen de la misma.

En el primer capítulo comienza a extender este concepto al espacio. En la introducción, el espacio es sagrado si en él se experimentan hierofanías: una colina, la sombra de un árbol, un abrigo de una montaña o una cueva. Sin embargo, en este capítulo Eliade comienza a introducir al hombre como creador de espacios sagrados y por tanto constructor de ambientes que son capaces de proporcionar esa hierofanía o experiencia de lo sagrado; este ritual trata de reproducir la obra de los dioses. Eliade afirma

> *Para vivir en el Mundo* hay que *fundarlo* (p. 18)

El Mundo, como oposición al caos, crea un *punto fijo*, un centro absoluto, en torno al cual se organiza la existencia. Y estos lugares existen se hayan fundado o no, se crean a través de la experiencia; incluso fuera del Mundo existen estos lugares sagrados, lugares que conforman la Realidad. Incluso existen ciertos ritos que ayudan a la transición hacia esos lugares, por ejemplo, cuando se entra en el hogar, o "guardianes" de esas puertas, que se usan en muchas culturas o incluso en nuestros días; Eliade:

> Todo espacio sabrado implica una hierofanía, una irrupción de lo sagrado...

Que hace que el espacio "sea cualitativamente diferente". El espacio sagrado se manifiesta como un Cosmos, en contraposición al Caos exterior, "donde habitan los monstruos". Lo que no es "nuestro Mundo" ni siquiera es Mundo: hasta que no se consagra un espacio, no se puede apropiar de él.

Y este ritual de consagración es una repetición de la *cosmogonía* o creación del mundo. Si los mitos de una cultura narran esa creación a través de un artefacto o lugar, el transporte, la ocupación de ese artefacto o lugar equivale a la creación del mundo *en el lugar donde ocurra*. Muchas veces se usa este concepto más en negativo que en positivo: se destruye o se demuele algún lugar o edificio consagrado para destruir simbólicamente una cultura. Aquí es precisamente donde Eliade introduce el concepto de "Axis Mundi", "el poste que sostiene el cielo o el Pilar del Mundo", también el "Centro del Mundo": el espacio sagrado es una apertura que comunica con el Más Allá, no sólo el cielo, sino también en ocasiones el infierno. Eso hace que en muchos casos se trate de montañas, postes, torres o piedras. El hombre, al organizar su espacio alrededor del eje/centro del mundo, está literalmente más cerca del cielo que cualquier otro ser.

Dado que la construcción equivale a una cosmogonía, la mayoría de las culturas establecen una serie de tradiciones que tratan de igualar la construcción de un edificio sagrado a la creación del mundo por parte de la deidad, y esa tradición muchas veces tiene forma de sacrificio; esto se refleja en muchos casos en mitos o en objetos como reliquias de mártires sobre los cuales se crean iglesias. En general, como afirma Eliade,

> La arquitectura sagrada no ha hecho sino recoger y desarrollar el simbolismo cosmológico [...] de las habitaciones primitivas (p. 44)

Las iglesias, por tanto, simbolizan el Mundo/Cosmos; pero a su vez lo encarnan: sus cuatro partes simbolizan las direcciones cardinales, pro ejemplo, y cada una de ellas tiene su significado: el Oeste es la oscuridad y la muerte, el este el renacimiento y la luz. Con esta referencia a acontecimientos periódicos también se prefigura la referencia a un *tiempo sagrado*.

A este tiempo sagrado se le dedica el segundo capítulo. A diferencia del profano, el tiempo sagrado es reversible, es una "reactualización de un acontecimiento pasado". Pero el tiempo sagrado tiene un lugar, y los nombres de esos lugares a veces reflejan su relación. Eliade habla de la similitud entre "templun" y "tempus", y también el hecho de que en muchas lenguas la palabra para Mundo y Año sean la misma. Como el año se renueva, así se renueva el Mundo todos los años, y se recorren las cuatro estaciones, que son como los cuatro puntos cardinales.

La misma cosmogonía marca también esa renovación que sucede todos los años, como en el Enuma Elish, el poema de la creación babilónico, cuya recitación marcaba el principio del año, e iba acompañado de una serie de rituales relacionados con el triunfo del bien frente al mal. Se marca con ello la reanudación del Tiempo, que de esta forma se purifica y se renueva.

Por eso en todas las religiones y culturas hay fiestas que simbólicamente extraen a la persona del tiempo profano y la sitúan en un tiempo sagrado, purificador y lleno de significado, lleno de Realidad, y estas fiestas siempre están relacionadas con una cosmogonía, un tiempo mítico; al situarte en este tiempo sagrado, la persona viaja al "illud tempus" y se hace *contemporánea* de los dioses.

Pero este mito es, también, una *ontofanía*, una revelación del ser o de la realidad, porque lo sagrado es lo real por excelencia. La persona se convierte en una persona real en tanto en cuanto comparte y vive *en* ese mito.

Los mitos, por otro lado, igual que el Año/Mundo, tienen una estructura circular: a la creación del mundo le acompaña su destrucción (o destrucción parcial a través de alguna catástrofe tal como un diluvio); a la muerte del dios le acompaña su resurrección. El *eterno retorno* dota de estructura y de ritmo al tiempo sagrado, que se repite globalmente y también en alguno de sus aspectos

> La duración cósmica es repetición y *anakylesis*, eterno retorno (p. 82)

Y esa repetición de la teofanía también convierte la Historia en teología, 

> Todo lo que ha sucedido en la Historia *debía suceder así* (p. 84)

Dado que estas teofanías ocurren periódicamente, acercándonos a la Realidad, y a que el hombre vive en la realidad en minúsculas, se busca una forma de explicar esa realidad acudiendo a la Realidad. Y esto lleva a la tercera parte del libro que habla de la sacralidad de la naturaleza y la "religión cósmica".

> Si se venera a una piedra sagrada es porque es *sagrada* y no porque sea *piedra*.

La misma lejanía, inalcanzabilidad, del cielo es muestra de su carácter sagrado; los dioses *uranios* existen en casi todas las religiones; la luz que procede del mismo también se reviste a veces de carácter sagrado; en muchos idiomas la palabra para dios o divinidad es la misma que se usa para luz, o para el adjetivo "brillante"; la misma palabra cielo en muchos idiomas es equivalente a dios, y en español se usa con frecuencia la expresión "gracias al cielo".

Pero por su propia inalcanzabilidad y aislamiento, muchas culturas simplemente lo consideran algo inasible y con el que no merece la pena relacionarse; pero eso hace que se interese por la *hierofanías de la Vida*, es decir, las pequeñas experiencias cotidianas que acercan a lo sagrado: la agricultura (que en muchas culturas ha sido un regalo de un dios a los hombres, como Enki en Sumeria), la fertilidad o las aguas.

El agua es el origen de la vida según la ciencia, pero también según muchas religiones, que contienen *hidrogonías* en las que el género humano surge de las aguas. A través del bautismo, se sumerge a la persona en las aguas, naciendo de nuevo, repitiendo así el mito del origen en el que "el espíritu de Dios se mecía sobre las aguas" y del Diluvio, en el que Dios instruyó a Noé sobre la creación del Arca para salvar la Humanidad.

Esta tercera parte se extiende, por otro lado, en diferentes tradiciones compartidas por diversas religiones, cuyo interés es principalmente antropológico: ritos de fertilidad, de matrimonio, o al árbol cósmico, por ejemplo. Podemos pararnos en el *matrimonio sagrado* o *hierogamia*, cuyo modelo divino es el de la fecundación de la tierra por el cielo, o de la Tierra-Madre por el dios. Esta *hierogamia* tiene una extensión en la mística del barroco español, pero también en la iconografía y el vocabulario pictórico usado en diferentes mitos como el de Dánae, pero también en matrimonio místico de Santa Catalina de Siena y otras santas.

De la misma forma, la cuarta parte sobre la existencia humana, es la más corta y tiene una relevancia relativamente menor para la asignatura de Vocabulario. Principalmente se refiere a cómo es imposible eliminar totalmente de la vida cotidiana lo sagrado, y como las ideologías "racionales" que tratan de hacerlo en realidad lo sustituyen por otro tipo de experiencias "sagradas" que en realidad sirven al poder y a la subyugación del ser humano. Quizás la referencia al fenómeno de la iniciación como revelación inicial de lo sagrado, la muerte y la sexualidad, como un paso a través del umbral de la vida, sea lo más pertinente a un estudio del arte y de su historia. En muchos casos, esta iniciación hace referencia al tiempo sagrado, con una muerte y resurrección del iniciado, en otros casos, a una experiencia de una deidad *dema* que comparte su cuerpo con el iniciado, como sucede con la comunión.

Esta parte finaliza con lo una descripción de lo sacro y lo profano en el mundo moderno. Eliade dice:

> El hombre moderno que se siente [...] arreligioso dispone aún de toda una mitología camuflada y numerosos ritualismos degradados. (p. 150)

El libro termina diciendo:

> Aquí también comienza la problemática propia del filósofo, del psicólogo, incluso del teólogo (p. 157)

## Crítica y opinión personal

En esta dirección https://www.goodreads.com/review/show/6903869837 he puesto mi reseña, calificándolo con tres estrellas sobre cinco en Goodreads. En general, el libro puede tener más interés desde el punto de vista de la historia de las religiones que desde la historia del arte. Aunque proporciona una serie de elementos para interpretar la arquitectura sagrada y algunos elementos de la iconografía, sobre todo relacionados con la religión y la mitología, lo hace de una forma más extensa y menos divulgativa que muchos otros manuales dedicados exclusivamente a esta labor.

El pensamiento actual no está exento de críticas, tanto al enfoque como al contenido. Al buscar información para esta reseña, se encontraba mucha entre grupúsculos seudo-místicos; de hecho, hay una cierta relación entre el pensamiento de Eliade y el de otros autores esotéricos como Agrippa [@mañas2003de], un autor que explícitamente equipara la ciencia con la vanidad, de la misma forma que Eliade critica veladamente la racionalidad moderna como incapaz de proporcionar una experiencia de la realidad en todas sus formas. Otros pensadores, como Whitmarsh [@whitmarsh2015battling], ponen de relieve que el ateísmo concebido no como algo en contra de la religión, sino como una visión del mundo (*weltanschauung*) que se basa solo en la experiencia sensorial y su elaboración racional, ha existido durante toda la historia y ha convivido con el pensamiento religioso y los mitos. Si bien, posiblemente, no haya tenido tan buena publicidad como este último. Entre estos podríamos también citar a Feuerbach [@feuerbach1848das], que afirma que "Teología es antropología", y que en realidad las hierofanías/ontofanías/teofanías no son ningún tipo de experiencia trascendente, sino simples relatos que la persona crea para su propio consumo, y que desde nuestro punto de vista nos pueden servir para entendernos como humanidad, pero poco más.

Por otro lado, el pensamiento de Eliade tiene una íntima relación con otros filósofos y escritores del mismo siglo. Giovanni Papini, en [@papini1931gog], describe a una persona que va buscando una experiencia transcendental, y que finalmente la encuentra en una niña que comparte un trozo de pan. La simple generosidad y la inocencia están más relacionada con lo sacro que cualquier conversación con los poderosos o incluso los sacerdotes de diferentes religiones. En esta búsqueda de lo sagrado, el protagonista de "Gog" trata de experimentar la verdadera Realidad que Eliade describió muchos años más tarde.

El libro, en general, no deja de tener utilidad para interpretar obras artísticas y arquitectónicas; incluso se le ha encontrado una aplicación a estudios cinematográficos [@He2020] para interpretar la arquitectura irreal que aparece en películas de ciencia ficción como Blade Runner. Sobre todo es valioso porque la religión y sus diferentes manifestaciones fueron, hasta prácticamente el siglo XVIII en Occidente, la principal fuente de inspiración para la pintura, escultura y arquitectura. Sobre todo es valioso en el sentido que proporciona metáforas visuales muy potentes para interpretar la obra: el eterno retorno, la hierofanía, el *axis mundi*, son conceptos relativamente sencillos de asimilar y de proyectar en la interpretación de una obra artística. Sin embargo, el problema es que en este libro en particular están rodeados de otro conceptos sin mayor interés, por eso la experiencia de lectura de este libro no puede calificarse como totalmente positiva.


## Notas

Los fuentes de este trabajo están en https://github.com/JJ/sagrado-y-profano


## Bibliografía
